# pytest.ini
[pytest]
# where to look for tests by default
testpaths = tests

# run ALL tests, show every test name, stream prints live, full summary, slowest tests
addopts = -vv -s -r a --color=yes --durations=10

# (optional) silence noisy deprecations
filterwarnings =
    ignore::DeprecationWarning:pydantic\..*
    ignore:.*on_event.*:DeprecationWarning:fastapi\..*

# (optional) document custom markers
markers =
    smoke: quick checks you can run during development
